// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewJob struct {
	UserID      int     `json:"userId"`
	Description *string `json:"description,omitempty"`
	File        string  `json:"file"`
	OnGoing     bool    `json:"onGoing"`
	Completed   bool    `json:"completed"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
